// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaqBIYhgoSMhJoJ_W-brBpAVH5fijQmI',
    appId: '1:798629020650:web:1868ae63d0b051d002a893',
    messagingSenderId: '798629020650',
    projectId: 'flutterfinalproject-83f7d',
    authDomain: 'flutterfinalproject-83f7d.firebaseapp.com',
    storageBucket: 'flutterfinalproject-83f7d.appspot.com',
    measurementId: 'G-XH3SPCF2S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvZD7hyJZwePi7X6UUNjsi65hl1WlArpM',
    appId: '1:798629020650:android:fc4921ff9aafd23602a893',
    messagingSenderId: '798629020650',
    projectId: 'flutterfinalproject-83f7d',
    storageBucket: 'flutterfinalproject-83f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BwMKx2KD3dJu9yWfyIsYQkXTQ-B7gZQ',
    appId: '1:798629020650:ios:2def83eae5fd2b4c02a893',
    messagingSenderId: '798629020650',
    projectId: 'flutterfinalproject-83f7d',
    storageBucket: 'flutterfinalproject-83f7d.appspot.com',
    iosClientId: '798629020650-v2b9f7m5oj5hgvrj8e5kkg5ap8ctbcqs.apps.googleusercontent.com',
    iosBundleId: 'com.ntou.flutterFinal',
  );

}